show_plots_title = False
default_comparison_precision = 200_000
omp_results_file = 'results/omp-2022-12-25-n0.csv'
mpi_results_file = 'results/mpi-2022-12.csv'
hyb_results_file = 'results/hyb-2023-1-1.csv'
path_to_save_plots = 'plots/'
path_to_save_tables = 'tables/'
mpi_algorithms_excluded = ['GMP-CHD-SME-CHTXX']
omp_algorithms_excluded = ['GMP-CHD-SME-CHTXX']
color_lines = ['#5383EC', '#D85040', '#F2BF41', '#34A853', '#FF6D01', '#46BDC6', '#9900FF', '#804000', '#FF0080', '#000000']
marker_styles = ['o', '^', 's', 'd', 'p', 'h', '*', 'x', '+', '1']
font_title = {'family': 'serif', 'color': 'black', 'weight': 'bold', 'size': 13}
font_subtitle = {'family': 'serif', 'color': 'black', 'weight': 'normal', 'size': 12}
font_text = {'family': 'serif', 'color': 'black', 'weight': 'normal', 'size': 10, 'alpha': 0.8}
